name = "labledger-desk"
main = "src/index.js"
compatibility_date = "2026-09-19"
workers_dev = true

[triggers]
crons = ["*/5 * * * *"]

[vars]
SITE_URL = "https://labledgerdesk.pages.dev"
CHANNEL_URL = "https://t.me/labledgerdesk"

[[kv_namespaces]]
binding = "DESK"
id = "80019ea38abb4797b802973d3f4fe161"
